# Generated by Django 5.2.7 on 2025-10-28 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('HR', 'Human Resources'), ('MKT', 'Marketing'), ('R&D', 'Research & Development'), ('SALES', 'Sales'), ('FIN', 'Finance'), ('IT', 'Information Technology'), ('ADMIN', 'Administration'), ('CS', 'Customer Service'), ('ACC', 'Accounting'), ('QA', 'Quality Assurance'), ('MNT', 'Maintenance'), ('BIZ', 'Business'), ('DES', 'Designing'), ('LEAD', 'Leadership'), ('LEGAL', 'Legal'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='leavetype',
            name='name',
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='admin', max_length=20),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('EMERGENCY', 'Emergency Leave'), ('SICK', 'Sick Leave'), ('PATIENT_CARE', 'Patient Care Leave'), ('SPECIAL', 'Special Leave'), ('BEREAVEMENT', 'Bereavement Leave')], default='SPECIAL', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='action_type',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
