# Generated by Django 5.2.7 on 2025-10-28 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_employee_department_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_allowed',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
