# Generated by Django 5.2.7 on 2025-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_employee_role_alter_leavetype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_allowed',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
