# Generated by Django 5.2.7 on 2025-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_leavetype_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='total_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default=None, max_length=20, null=True),
        ),
    ]
