# Generated by Django 5.2.7 on 2025-10-30 10:06

from django.db import migrations

def create_leave_types(apps, schema_editor):
    # Get `LeaveType` model
    LeaveType = apps.get_model('main_app', 'LeaveType')
    
    # Leave Types Data
    leave_types_data = [
        {
            'type': 'ANNUAL',
            'description': 'Regular annual vacation for employees',
            'max_days_allowed': 30
        },
        {
            'type': 'EMERGENCY', 
            'description': 'Urgent leave for unforeseen circumstances',
            'max_days_allowed': 3
        },
        {
            'type': 'SICK',
            'description': 'Medical leave for health-related issues', 
            'max_days_allowed': 30
        },
        {
            'type': 'PATIENT_CARE',
            'description': 'Leave to accompany and care for sick family members',
            'max_days_allowed': 5
        },
        {
            'type': 'SPECIAL',
            'description': 'Exceptional leave for special circumstances',
            'max_days_allowed': 10000  # No limit
        },
        {
            'type': 'BEREAVEMENT',
            'description': 'Leave in case of family member death',
            'max_days_allowed': 5
        },
    ]
    
    # Create each leave type
    for data in leave_types_data:
        LeaveType.objects.create(
            type=data['type'],
            description=data['description'],
            max_days_allowed=data['max_days_allowed']
        )
    
    print("✅ Leave types created successfully!")


def reverse_leave_types(apps, schema_editor):
    LeaveType = apps.get_model('main_app', 'LeaveType')
    LeaveType.objects.all().delete()
    print("🗑️ Leave types deleted!")


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_leaverequest_total_days_alter_leaverequest_status'),
    ]

    operations = [
        migrations.RunPython(create_leave_types, reverse_leave_types),
    ]
