# Generated by Django 5.2.7 on 2025-10-31 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20251030_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavebalance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='reset_date',
            field=models.DateField(default=datetime.date(2024, 12, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='warning_threshold',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_warning_displayed',
            field=models.BooleanField(default=False, help_text='Whether warning was shown to employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='warning_message',
            field=models.TextField(blank=True, help_text='Warning message if balance is insufficient'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('EMERGENCY', 'Emergency Leave'), ('SICK', 'Sick Leave'), ('PATIENT_CARE', 'Patient Care Leave'), ('SPECIAL', 'Special Leave'), ('BEREAVEMENT', 'Bereavement Leave')], max_length=20, unique=True),
        ),
    ]
