# Generated by Django 5.2.7 on 2025-11-05 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_leavebalance_is_active_leavebalance_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
    ]
